#!/bin/sh

echo "playradio $1 $2" > /tmp/playradio.log

/usr/local/bin/ecp mp3player QUIT
/usr/local/bin/ecp sonicaApp EXIT
touch /tmp/stop.vlc
if [ -f /tmp/vlc.runs ]; then
    # There is a vlc running... stop it.
    touch /tmp/stop.vlc
    sleep 3
    touch /tmp/stop.vlc
fi

case `/usr/bin/basename $1` in
    'sonica')
        echo "\"$1\" -b -i -n -f \"$2\" &" >> /tmp/playradio.log
        cd `dirname $1`
        echo `pwd` >> /tmp/playradio.log
        "$1" -b -f "$2" &
        echo "playradio $?" >> /tmp/playradio.log
        RESULT=`/usr/local/bin/ecp sonicaApp PLAY`
        while [ "$RESULT" == "sonicaApp: unknown ecp command" ]; do
            sleep 1
            RESULT=`/usr/local/bin/ecp sonicaApp PLAY`
        done
        echo "playradio $? $RESULT" >> /tmp/playradio.log
        ;;
    'vlc.sdesk')
        echo "\"$1\" --intf=telnet \"$2\"" >> /tmp/playradio.log
        cd `dirname $1`
        echo `pwd` >> /tmp/playradio.log
        "$1" --intf=telnet "$2"
        echo "playradio $?" >> /tmp/playradio.log
        ;;
    *)
        echo "Unsupported player $1" >> /tmp/playradio.log
        ;;
esac

# eof
