#!/bin/sh

echo "stopplay" > /tmp/stopplay.log

/usr/local/bin/ecp mp3player QUIT
/usr/local/bin/ecp sonicaApp exit
touch /tmp/stop.vlc
if [ -f /tmp/vlc.runs ]; then
    # There is a vlc running... stop it.
    touch /tmp/stop.vlc
    sleep 3
    touch /tmp/stop.vlc
fi

# eof

