#!/bin/sh

if [ -f /tmp/component ]; then
    rm /tmp/component
    /usr/local/bin/ecp system videomode svideo 480i
else
    touch /tmp/component
    /usr/local/bin/ecp system videomode component 480i
fi
