/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Maximum supported data alignment */
#define ATTRIBUTE_ALIGNED_MAX 64

/* Define if \$CC groks 3D Now! inline assembly. */
/* #undef CAN_COMPILE_3DNOW */

/* Define if \$CC groks AltiVec inline assembly. */
/* #undef CAN_COMPILE_ALTIVEC */

/* Define if your compiler groks C AltiVec extensions. */
/* #undef CAN_COMPILE_C_ALTIVEC */

/* Define if \$CC groks MMX inline assembly. */
/* #undef CAN_COMPILE_MMX */

/* Define if \$CC groks MMX EXT inline assembly. */
/* #undef CAN_COMPILE_MMXEXT */

/* Define if \$CC groks SSE inline assembly. */
/* #undef CAN_COMPILE_SSE */

/* The ./configure command line */
#define CONFIGURE_LINE "./configure --enable-static --enable-shared --disable-plugins --prefix=/usr --disable-sdl --enable-mad --with-libmad-tree=/mnt/smb/terra/video/New/Develop/src/vlc-0.8.1/src/libmad-0.15.lb --enable-libmpeg2 --with-libmpeg2-tree=/mnt/smb/terra/video/New/Develop/src/vlc-0.8.1/src/mpeg2dec-0.4.0 --disable-dvbpsi --disable-vcd --disable-vcdx --disable-cdda --disable-cddax --disable-libcdio --disable-libcddb --disable-dvd --disable-dvdread --disable-dvdnav --disable-dvdplay --disable-dshow --disable-directx --disable-wingdi --disable-waveout --disable-macosx --disable-coreaudio --disable-quicktime --disable-qnx --disable-ncurses --disable-corba --disable-mozilla --disable-mga --disable-svgalib --disable-ggi --disable-glide --disable-aa --disable-caca --disable-qte --disable-qt_video --disable-livedotcom --disable-corba --disable-v4l --disable-pvr --disable-satellite --disable-dvb --disable-slp --disable-speex --disable-ffmpeg --disable-ogg --disable-vorbis --disable-tremor --disable-tarkin --disable-theora --disable-mod --disable-mkv --disable-a52 --disable-dts --disable-faad --disable-flac --disable-lirc --disable-joystick --disable-x11 --disable-xvideo --disable-xosd --disable-gtk --disable-gnome --disable-esd --disable-wxwindows --disable-kde --disable-arts --disable-pda --disable-opie --disable-cmml --disable-skins --disable-skins2 --disable-fribidi --disable-freetype --disable-sout --disable-oss --disable-alsa --disable-fb --disable-visual --disable-goom --enable-hd1000a --disable-hd1000v CFLAGS=-I/usr/tools/roku/include -I/usr/include -I/usr/local/include -I/usr/local/include/roku CXXFLAGS= CPPFLAGS= LDFLAGS=-L/usr/tools/roku/mipsel-linux/lib -L/lib -L/usr/local/lib -Wl,-rpath-link -Wl,/usr/local/lib"

/* Copyright string */
#define COPYRIGHT_MESSAGE "VLC media player - version 0.8.1 Janus - (c) 1996-2004 VideoLAN"

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define if <X11/extensions/dpms.h> defines DPMSInfo. */
/* #undef DPMSINFO_IN_DPMS_H */

/* Define if you want the HTTP dameon support */
#define ENABLE_HTTPD 1

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
#define ENABLE_NLS 1

/* Define if you want the stream output support */
/* #undef ENABLE_SOUT */

/* Define if you want utf8 support */
/* #undef ENABLE_UTF8 */

/* Define if you want the VideoLAN manager support */
#define ENABLE_VLM 1

/* Define to 1 if you have the <a52dec/a52.h> header file. */
/* #undef HAVE_A52DEC_A52_H */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define if ALSA is at least rc4 */
/* #undef HAVE_ALSA_NEW_API */

/* Define to 1 if you have the <altivec.h> header file. */
/* #undef HAVE_ALTIVEC_H */

/* Define to 1 if you have the <ApplicationServices/ApplicationServices.h>
   header file. */
/* #undef HAVE_APPLICATIONSERVICES_APPLICATIONSERVICES_H */

/* Define to 1 if you have the <argz.h> header file. */
#define HAVE_ARGZ_H 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `asprintf' function. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have the `atof' function. */
#define HAVE_ATOF 1

/* Define to 1 if you have the `atoll' function. */
#define HAVE_ATOLL 1

/* Support for __attribute__((format())) with function pointers */
/* #undef HAVE_ATTRIBUTE_FORMAT */

/* Support for __attribute__((packed)) for structs */
#define HAVE_ATTRIBUTE_PACKED 1

/* Define to 1 if you have the <Carbon/Carbon.h> header file. */
/* #undef HAVE_CARBON_CARBON_H */

/* Define to 1 if you have the <cascade/graphics/CascadeBitmap.h> header file.
   */
/* #undef HAVE_CASCADE_GRAPHICS_CASCADEBITMAP_H */

/* Define to 1 if you have the <cascade/graphics/CascadeScreen.h> header file.
   */
/* #undef HAVE_CASCADE_GRAPHICS_CASCADESCREEN_H */

/* Define for the CD-DA plugin using libcdio */
/* #undef HAVE_CDDAX */

/* Define to 1 if you have the <Cocoa/Cocoa.h> header file. */
/* #undef HAVE_COCOA_COCOA_H */

/* Define to 1 if you have the `connect' function. */
#define HAVE_CONNECT 1

/* Define to 1 if you have the <CoreAudio/CoreAudio.h> header file. */
/* #undef HAVE_COREAUDIO_COREAUDIO_H */

/* Define to 1 if you have the <cthreads.h> header file. */
/* #undef HAVE_CTHREADS_H */

/* Define to 1 if you have the `ctime_r' function. */
#define HAVE_CTIME_R 1

/* Define to 1 if you have the `daemon' function. */
#define HAVE_DAEMON 1

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
#define HAVE_DCGETTEXT 1

/* Define to 1 if you have the <ddraw.h> header file. */
/* #undef HAVE_DDRAW_H */

/* Define if <time.h> defines nanosleep. */
#define HAVE_DECL_NANOSLEEP 1

/* Define to 1 if you have the
   <deschutes/libraries/hdmachinex225/PCMAudioPlayer.h> header file. */
#define HAVE_DESCHUTES_LIBRARIES_HDMACHINEX225_PCMAUDIOPLAYER_H 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if you have the BeOS dl */
/* #undef HAVE_DL_BEOS */

/* Define if you have the GNU dld library */
/* #undef HAVE_DL_DLD_LINK */

/* Define if you have the dlopen API */
#define HAVE_DL_DLOPEN 1

/* Define if you have the Darwin dyld API */
/* #undef HAVE_DL_DYLD */

/* Define to 1 if you have the <dl.h> header file. */
/* #undef HAVE_DL_H */

/* Define if you have the shl_load API */
/* #undef HAVE_DL_SHL_LOAD */

/* Define if you have Windows' LoadLibrary */
/* #undef HAVE_DL_WINDOWS */

/* Define to 1 if you have the <dshow.h> header file. */
/* #undef HAVE_DSHOW_H */

/* Define to 1 if you have the <dts.h> header file. */
/* #undef HAVE_DTS_H */

/* Define to 1 if you have the <dvbpsi/dr.h> header file. */
/* #undef HAVE_DVBPSI_DR_H */

/* Define to 1 if you have the <dvdread/dvd_reader.h> header file. */
/* #undef HAVE_DVDREAD_DVD_READER_H */

/* Define to 1 if you have the <ebml/EbmlVersion.h> header file. */
/* #undef HAVE_EBML_EBMLVERSION_H */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <faad.h> header file. */
/* #undef HAVE_FAAD_H */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `feof_unlocked' function. */
#define HAVE_FEOF_UNLOCKED 1

/* Define to 1 if you have the <ffmpeg/avcodec.h> header file. */
/* #undef HAVE_FFMPEG_AVCODEC_H */

/* Define to 1 if you have the `fgets_unlocked' function. */
#define HAVE_FGETS_UNLOCKED 1

/* Define to 1 if you have the <FLAC/stream_decoder.h> header file. */
/* #undef HAVE_FLAC_STREAM_DECODER_H */

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getc_unlocked' function. */
#define HAVE_GETC_UNLOCKED 1

/* Define to 1 if you have the `getegid' function. */
#define HAVE_GETEGID 1

/* Define to 1 if you have the `getenv' function. */
#define HAVE_GETENV 1

/* Define to 1 if you have the `geteuid' function. */
#define HAVE_GETEUID 1

/* Define to 1 if you have the `getgid' function. */
#define HAVE_GETGID 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `gethostbyname2' function. */
#define HAVE_GETHOSTBYNAME2 1

/* Define to 1 if you have the `getnameinfo' function. */
#define HAVE_GETNAMEINFO 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* getopt support */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `getuid' function. */
#define HAVE_GETUID 1

/* Define to 1 if you have the <GL/glx.h> header file. */
/* #undef HAVE_GL_GLX_H */

/* Define to 1 if you have the <GL/gl.h> header file. */
/* #undef HAVE_GL_GL_H */

/* Define to 1 if you have the `gmtime_r' function. */
#define HAVE_GMTIME_R 1

/* Define to 1 if you have libgnutls */
/* #undef HAVE_GNUTLS */

/* Define to 1 if you have the <goom/goom.h> header file. */
/* #undef HAVE_GOOM_GOOM_H */

/* Define if you have the HAL library */
/* #undef HAVE_HAL */

/* Define if you have the iconv() function. */
#define HAVE_ICONV 1

/* Define to 1 if you have the <id3tag.h> header file. */
/* #undef HAVE_ID3TAG_H */

/* Define to 1 if you have the `if_nametoindex' function. */
#define HAVE_IF_NAMETOINDEX 1

/* Define to 1 if you have the <image.h> header file. */
/* #undef HAVE_IMAGE_H */

/* Define if we use the local libintl */
/* #undef HAVE_INCLUDED_GETTEXT */

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if <inttypes.h> exists, doesn't clash with <sys/types.h>, and
   declares uintmax_t. */
#define HAVE_INTTYPES_H_WITH_UINTMAX 1

/* For FreeBSD VCD support */
/* #undef HAVE_IOC_TOC_HEADER_IN_SYS_CDIO_H */

/* Define to 1 if you have the `isatty' function. */
#define HAVE_ISATTY 1

/* Define to 1 if you have the <jpeglib.h> header file. */
/* #undef HAVE_JPEGLIB_H */

/* Define to 1 if you have the <kernel/OS.h> header file. */
/* #undef HAVE_KERNEL_OS_H */

/* Define to 1 if you have the <kernel/scheduler.h> header file. */
/* #undef HAVE_KERNEL_SCHEDULER_H */

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
#define HAVE_LANGINFO_CODESET 1

/* Define to 1 if you have the <langinfo.h> header file. */
#define HAVE_LANGINFO_H 1

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define if you have ffmpeg's libavformat. */
/* #undef HAVE_LIBAVFORMAT */

/* Define this if you have libcddb installed */
/* #undef HAVE_LIBCDDB */

/* Define to 1 if you have the <libmodplug/modplug.h> header file. */
/* #undef HAVE_LIBMODPLUG_MODPLUG_H */

/* Define if you have the PNG library: libpng */
/* #undef HAVE_LIBPNG */

/* Define to 1 if you have the `pth' library (-lpth). */
/* #undef HAVE_LIBPTH */

/* Define to 1 if you have the `st' library (-lst). */
/* #undef HAVE_LIBST */

/* Define to 1 if you have the <libtar.h> header file. */
/* #undef HAVE_LIBTAR_H */

/* Define to 1 if you have the `xml2' library (-lxml2). */
/* #undef HAVE_LIBXML2 */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <linux/dvb/frontend.h> header file. */
/* #undef HAVE_LINUX_DVB_FRONTEND_H */

/* Define to 1 if you have the <linux/dvb/version.h> header file. */
/* #undef HAVE_LINUX_DVB_VERSION_H */

/* Define to 1 if you have the <linux/fb.h> header file. */
/* #undef HAVE_LINUX_FB_H */

/* Define to 1 if you have the <linux/version.h> header file. */
#define HAVE_LINUX_VERSION_H 1

/* Define to 1 if you have the <linux/videodev.h> header file. */
/* #undef HAVE_LINUX_VIDEODEV_H */

/* Define to 1 if you have the <liveMedia.hh> header file. */
/* #undef HAVE_LIVEMEDIA_HH */

/* Define to 1 if you have the `load_add_on' function. */
/* #undef HAVE_LOAD_ADD_ON */

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define to 1 if you have the `lrintf' function. */
/* #undef HAVE_LRINTF */

/* Define to 1 if you have the `lseek' function. */
#define HAVE_LSEEK 1

/* Define to 1 if you have the <machine/param.h> header file. */
/* #undef HAVE_MACHINE_PARAM_H */

/* Define to 1 if you have the <machine/soundcard.h> header file. */
/* #undef HAVE_MACHINE_SOUNDCARD_H */

/* Define to 1 if you have the <mach-o/dyld.h> header file. */
/* #undef HAVE_MACH_O_DYLD_H */

/* Define to 1 if you have the <mad.h> header file. */
#define HAVE_MAD_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <matroska/KaxAttachments.h> header file. */
/* #undef HAVE_MATROSKA_KAXATTACHMENTS_H */

/* Define to 1 if you have the <matroska/KaxVersion.h> header file. */
/* #undef HAVE_MATROSKA_KAXVERSION_H */

/* Define to 1 if you have the `memalign' function. */
#define HAVE_MEMALIGN 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mempcpy' function. */
#define HAVE_MEMPCPY 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the <mozilla-config.h> header file. */
/* #undef HAVE_MOZILLA_CONFIG_H */

/* Define to 1 if you have the <mpeg2dec/mpeg2.h> header file. */
/* #undef HAVE_MPEG2DEC_MPEG2_H */

/* Define to 1 if you have the `munmap' function. */
#define HAVE_MUNMAP 1

/* Define if nanosleep is available. */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <net/if.h> header file. */
#define HAVE_NET_IF_H 1

/* Define to 1 if you have the `nl_langinfo' function. */
#define HAVE_NL_LANGINFO 1

/* Define to 1 if you have the <nl_types.h> header file. */
#define HAVE_NL_TYPES_H 1

/* Define to 1 if you have the `NSLinkModule' function. */
/* #undef HAVE_NSLINKMODULE */

/* Define to 1 if you have the <ogg/ogg.h> header file. */
/* #undef HAVE_OGG_OGG_H */

/* Define to 1 if you have the <Ph.h> header file. */
/* #undef HAVE_PH_H */

/* Define to 1 if you have the <png.h> header file. */
#define HAVE_PNG_H 1

/* Define to 1 if you have the `posix_memalign' function. */
#define HAVE_POSIX_MEMALIGN 1

/* Define to 1 if you have the <postproc/postprocess.h> header file. */
/* #undef HAVE_POSTPROC_POSTPROCESS_H */

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the `pthread_mutex_lock' function. */
/* #undef HAVE_PTHREAD_MUTEX_LOCK */

/* Define to 1 if you have the `putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the <qt.h> header file. */
/* #undef HAVE_QT_H */

/* Define to 1 if you have the <QuickTime/QuickTime.h> header file. */
/* #undef HAVE_QUICKTIME_QUICKTIME_H */

/* Define for the VCD plugin using libcdio/libvcdinfo */
/* #undef HAVE_SATELLITE */

/* For NetBSD VCD support */
/* #undef HAVE_SCSIREQ_IN_SYS_SCSIIO_H */

/* Define to 1 if you have the <SDL.h> header file. */
/* #undef HAVE_SDL_H */

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `send' function. */
#define HAVE_SEND 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `sigrelse' function. */
#define HAVE_SIGRELSE 1

/* Define to 1 if you have the <slp.h> header file. */
/* #undef HAVE_SLP_H */

/* Define if <sys/socket.h> defines socklen_t. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the <soundcard.h> header file. */
/* #undef HAVE_SOUNDCARD_H */

/* Define to 1 if you have the <speex.h> header file. */
/* #undef HAVE_SPEEX_H */

/* Define to 1 if you have the <stdbool.h> header file. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define if <stdint.h> exists, doesn't clash with <sys/types.h>, and declares
   uintmax_t. */
#define HAVE_STDINT_H_WITH_UINTMAX 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stpcpy' function. */
#define HAVE_STPCPY 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strcasestr' function. */
#define HAVE_STRCASESTR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `stricmp' function. */
/* #undef HAVE_STRICMP */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `stristr' function. */
/* #undef HAVE_STRISTR */

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strndup' function. */
#define HAVE_STRNDUP 1

/* Define to 1 if you have the `strnicmp' function. */
/* #undef HAVE_STRNICMP */

/* Define to 1 if you have the `strtod' function. */
#define HAVE_STRTOD 1

/* Define to 1 if you have the `strtof' function. */
#define HAVE_STRTOF 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define if <sys/time.h> defines struct timespec. */
#define HAVE_STRUCT_TIMESPEC 1

/* Define to 1 if you have the `swab' function. */
#define HAVE_SWAB 1

/* Define to 1 if you have the <sysfs/libsysfs.h> header file. */
/* #undef HAVE_SYSFS_LIBSYSFS_H */

/* Define to 1 if you have the <sys/dl.h> header file. */
/* #undef HAVE_SYS_DL_H */

/* Define to 1 if you have the <sys/int_types.h> header file. */
/* #undef HAVE_SYS_INT_TYPES_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/shm.h> header file. */
#define HAVE_SYS_SHM_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `textdomain' function. */
#define HAVE_TEXTDOMAIN 1

/* Define to 1 if you have the <theora/theora.h> header file. */
/* #undef HAVE_THEORA_THEORA_H */

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <toolame.h> header file. */
/* #undef HAVE_TOOLAME_H */

/* Define to 1 if you have the <tremor/ivorbiscodec.h> header file. */
/* #undef HAVE_TREMOR_IVORBISCODEC_H */

/* Define to 1 if you have the `tsearch' function. */
#define HAVE_TSEARCH 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have the unsigned long long type. */
#define HAVE_UNSIGNED_LONG_LONG 1

/* Support for variadic macros */
#define HAVE_VARIADIC_MACROS 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Define if <stdarg.h> defines va_copy. */
#define HAVE_VA_COPY 1

/* Define to 1 if you have the <vorbis/codec.h> header file. */
/* #undef HAVE_VORBIS_CODEC_H */

/* Define to 1 if you have the <vorbis/vorbisenc.h> header file. */
/* #undef HAVE_VORBIS_VORBISENC_H */

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <wx/wxprec.h> header file. */
/* #undef HAVE_WX_WXPREC_H */

/* Define to 1 if you have the <X11/extensions/dpms.h> header file. */
/* #undef HAVE_X11_EXTENSIONS_DPMS_H */

/* Define to 1 if you have the <X11/extensions/Xinerama.h> header file. */
/* #undef HAVE_X11_EXTENSIONS_XINERAMA_H */

/* Define to 1 if you have the <X11/extensions/Xv.h> header file. */
/* #undef HAVE_X11_EXTENSIONS_XV_H */

/* Define to 1 if you have the <X11/Xlib.h> header file. */
/* #undef HAVE_X11_XLIB_H */

/* Define to 1 if you have the <x264.h> header file. */
/* #undef HAVE_X264_H */

/* Define this if you have libXinerama installed */
/* #undef HAVE_XINERAMA */

/* Define if <xosd.h> is pre-1.0.0 */
/* #undef HAVE_XOSD_VERSION_0 */

/* Define if <xosd.h> is 1.0.x */
/* #undef HAVE_XOSD_VERSION_1 */

/* Define if <xosd.h> is 2.0.x */
/* #undef HAVE_XOSD_VERSION_2 */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Define to 1 if you have the `__argz_count' function. */
#define HAVE___ARGZ_COUNT 1

/* Define to 1 if you have the `__argz_next' function. */
#define HAVE___ARGZ_NEXT 1

/* Define to 1 if you have the `__argz_stringify' function. */
#define HAVE___ARGZ_STRINGIFY 1

/* Define if <stdarg.h> defines __va_copy. */
#define HAVE___VA_COPY 1

/* Define as const if the declaration of iconv() needs const. */
#define ICONV_CONST 

/* Define if integer division by zero raises signal SIGFPE. */
#define INTDIV0_RAISES_SIGFPE 1

/* Dynamic object extension */
#define LIBEXT ".so"

/* String suffix for module functions */
#define MODULE_SUFFIX "__0_8_1"

/* Symbol suffix for module functions */
#define MODULE_SYMBOL 0_8_1

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Define if <sys/param.h> defines ntohl. */
/* #undef NTOHL_IN_SYS_PARAM_H */

/* Name of package */
#define PACKAGE "vlc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "vlc"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "vlc 0.8.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "vlc"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.8.1"

/* Define if <inttypes.h> exists and defines unusable PRI* macros. */
/* #undef PRI_MACROS_BROKEN */

/* Define if <pthread.h> defines pthread_cond_t. */
#define PTHREAD_COND_T_IN_PTHREAD_H 1

/* Define if <pthread.h> defines pthread_once. */
#define PTHREAD_ONCE_IN_PTHREAD_H 1

/* Define if <pth.h> defines pth_init */
/* #undef PTH_INIT_IN_PTH_H */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* As a last resort we also test for SDL.h presence */
/* #undef SDL_INCLUDE_FILE */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if <strings.h> defines strncasecmp. */
#define STRNCASECMP_IN_STRINGS_H 1

/* Define if <st.h> defines st_init */
/* #undef ST_INIT_IN_ST_H */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "0.8.1"

/* Simple version string */
#define VERSION_MESSAGE "0.8.1 Janus"

/* big endian system */
/* #undef WORDS_BIGENDIAN */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `sockaddr' if <sys/socket.h> does not define. */
/* #undef sockaddr_storage */

/* Define to `sa_family' if <sys/socket.h> does not define. */
/* #undef ss_family */

/* Define to unsigned long or unsigned long long if <inttypes.h> and
   <stdint.h> don't define. */
/* #undef uintmax_t */
