#!/bin/sh

SRC="${PWD}/src"
ROKU=""

# configure mpeglib with --with-pic=no

#make distclean
#./bootstrap  --enable-mostly-builtin \
make clean
./configure --enable-static --enable-shared --disable-plugins \
  --prefix=${ROKU}/usr \
  --disable-sdl \
  --enable-mad --with-libmad-tree=${SRC}/libmad-0.15.lb \
  --enable-libmpeg2 --with-libmpeg2-tree=${SRC}/mpeg2dec-0.4.0 \
  --disable-dvbpsi \
  --disable-vcd --disable-vcdx --disable-cdda --disable-cddax --disable-libcdio --disable-libcddb \
  --disable-dvd --disable-dvdread --disable-dvdnav --disable-dvdplay \
  --disable-dshow --disable-directx --disable-wingdi --disable-waveout \
  --disable-macosx --disable-coreaudio --disable-quicktime \
  --disable-qnx \
  --disable-ncurses \
  --disable-corba \
  --disable-mozilla \
  --disable-mga \
  --disable-svgalib --disable-ggi --disable-glide \
  --disable-aa --disable-caca \
  --disable-qte --disable-qt_video \
  --disable-livedotcom \
  --disable-corba \
  --disable-v4l \
  --disable-pvr \
  --disable-satellite --disable-dvb \
  --disable-slp \
  --disable-speex \
  --disable-ffmpeg \
  --disable-ogg --disable-vorbis --disable-tremor --disable-tarkin --disable-theora \
  --disable-mod \
  --disable-mkv \
  --disable-a52 \
  --disable-dts \
  --disable-faad \
  --disable-flac \
  --disable-lirc --disable-joystick \
  --disable-x11 --disable-xvideo --disable-xosd \
  --disable-gtk --disable-gnome --disable-esd \
  --disable-wxwindows \
  --disable-kde --disable-arts \
  --disable-pda --disable-opie \
  --disable-cmml \
  --disable-skins --disable-skins2 \
  --disable-fribidi --disable-freetype \
  --disable-sout \
  --disable-oss --disable-alsa --disable-fb \
  --disable-visual --disable-goom \
  --enable-hd1000a --disable-hd1000v \
  CFLAGS="-I/usr/tools/roku/include -I${ROKU}/usr/include -I${ROKU}/usr/local/include -I${ROKU}/usr/local/include/roku" \
  CXXFLAGS="${CFLAGS}" \
  CPPFLAGS="${CFLAGS}" \
  LDFLAGS="-L/usr/tools/roku/mipsel-linux/lib -L${ROKU}/lib -L${ROKU}/usr/local/lib -Wl,-rpath-link -Wl,${ROKU}/usr/local/lib" && \
  make 
